### PR TITLE
Fix rtaudioerrortype compilation error

### PR DESCRIPTION
**Pull request by bkerler**
On compiling the code with latest rtaudio on Ubuntu 22.04 LTS, this error appears:

```
[ 83%] Building CXX object sink_modules/audio_sink/CMakeFiles/audio_sink.dir/src/main.cpp.o
/home/bjk/gnuradio/utils/SDRPlusPlus/sink_modules/audio_sink/src/main.cpp: In constructor ‘AudioSink::AudioSink(SinkManager::Stream*, std::string)’:
/home/bjk/gnuradio/utils/SDRPlusPlus/sink_modules/audio_sink/src/main.cpp:49:23: error: ‘struct RtAudio::DeviceInfo’ has no member named ‘probed’
   49 |             if (!info.probed) { continue; }
      |                       ^~~~~~
/home/bjk/gnuradio/utils/SDRPlusPlus/sink_modules/audio_sink/src/main.cpp: In member function ‘void AudioSink::doStart()’:
/home/bjk/gnuradio/utils/SDRPlusPlus/sink_modules/audio_sink/src/main.cpp:175:16: error: ‘RtAudioError’ does not name a type; did you mean ‘RtAudioErrorType’?
  175 |         catch (RtAudioError& e) {
      |                ^~~~~~~~~~~~
      |                RtAudioErrorType

```

This PR will fix this compiling error.

### CODE REVIEW

**Comment by AlexandreRouma** [comment]
you do realize that change will break it for everyone else right?

**Comment by STBoyden** [comment]
For future reference, the change made was a breaking change to an as of yet unreleased version of RtAudio that is still in development. Such a change would break compilation for everyone _but_ users of the development version of the RtAudio library. How you have the latest development build on 22.04 means you probably installed it manually at one point and forgot about it.

**Comment by bkerler** [comment]
Sorry I wanted to close the PR because I realized the issue is with the rtaudio repository having no stable branch, but you guys were faster ;) I've sent another pr for the readme to make it clear that only the released 5.x source tar ball is compatible with SDRPP.
