### ISSUE TITLE
rtaudio-6.0.0

### ISSUE THREAD

**Issue by srs4511351** [AlexandreRouma/SDRPlusPlus#1149]
**Feature description**
rtaudio-6.0.0 has been released, but SDR++ does not work with it.

When compiling, cmake found rtaudio, version 6.0.0

make has this error:
```
/home/dietpi/SDRPlusPlus/source_modules/audio_source/src/main.cpp: In member function ‘void AudioSourceModule::refresh()’:
/home/dietpi/SDRPlusPlus/source_modules/audio_source/src/main.cpp:93:26: error: ‘struct RtAudio::DeviceInfo’ has no member named ‘probed’
   93 |                 if (info.probed && info.inputChannels < 2) { continue; }
      |                          ^~~~~~
```
Will you consider making SDR++ work with rtaudio-5.2.0 and rtaudio-6.0.0?

----Steve

**Comment by AlexandreRouma** [comment]
I can't support 6.0 without dropping support for earlier versions since the author of RtAudio didn't add any compile-time way to check. Since almost all distros use rtaudio 5.2 and earlier, I won't support 6.0

**Comment by srs4511351** [comment]
cmake did list the version that it found. It said "Found rtaudio, version 6.0.0'

Some of the other apps like CubicSDR works with either version.

Maybe your best action is to add a warning in readme.md

----Steve

**Comment by srs4511351** [comment]
Thanks for offering to work on it.
In my opinion, if you can achieve the performance of RtAudio without it, you don't need it.
I will have it installed for the other SDR applications that need it.

**Comment by phoniclynx** [comment]
> Dear AlexandreRouma, I am writing to you because I am using Manjaro (derived from Arch) and I am having problems with RtAudio. Since Manjaro was rolling-release, it was updated to RtAudio 6 and SDR++ stopped working. Now I downgraded to RtAudio 5.2.0, compiled and SDR++ works like a charm.
> 
> I think this may be a temporary solution for those of us who have a rolling-release system that updates too much.
> 
> Best regards, Matías Saibene.

What did you do to install RtAudio 5.2.0? What was the command line to do it? (I'm in Manjaro too)

**Comment by AndreaVigarani** [comment]
> What did you do to install RtAudio 5.2.0? What was the command line to do it? (I'm in Manjaro too). I can only see an rtaudio 6 and no version 5 listed in the AUR

If you do not need rtaudio newer version for something else you can use
"manjaro-downgrade rtaudio"

**Comment by Mr-Precise** [comment]
I added the rtaudio 5.2 ([rtaudio5-exp](https://aur.archlinux.org/packages/rtaudio5-exp)) package to the AUR, sdrpp should now build.
Use with caution, it maybe break "backward compatibility" with other software...
Any suggestions welcome.

**Comment by srs4511351** [comment]
If other programs were compiled with rtaudio 6, they may have to be reinstalled and compiled with rtaudio 5.2 installed. Some may work as is.

**Comment by srs4511351** [comment]
I suggest that in you state in the instructions that SDR++ will work with the version of RtAudio that it was built with, 5.x or 6.x.
You can't just upgrade RtAudio and expect it to work with SDR++

**Comment by AlexandreRouma** [comment]
You realize that's how all compiled software works on unix-like systems right?

**Comment by srs4511351** [comment]
No, CubicSDR worked with RtAudio 6.0.1, having been compiled with RtAudio 5.2

In addition, not everyone knows that, it only takes a few words.
