### ISSUE TITLE
MacOS Mojave "dyld: lazy symbol binding failed: Symbol not found" on 1.0.3 and following

### ISSUE THREAD

**Issue by Topper69** [AlexandreRouma/SDRPlusPlus#387]
Hi,

To be able to compile on macos mojave 10.14.6, i'm have done the following modification (which works on 1.0.1) :

- replace headers "#include \<filesystem\>" by "#include <boost/filesystem.hpp>"

- replace "std::filesystem::" by "boost::filesystem::"

- replace "(!file.is_regular_file())" by "(!boost::filesystem::is_regular_file(file))"

(search and replace on all source files)

Compilation completed successfully.

Error on run time :
`
[2021-09-25 17:23:51.944] [info] SDR++ v1.0.4
dyld: lazy symbol binding failed: Symbol not found: __ZN5boost10filesystem6detail6statusERKNS0_4pathEPNS_6system10error_codeE
  Referenced from: /usr/local/lib/libsdrpp_core.dylib
  Expected in: flat namespace

dyld: Symbol not found: __ZN5boost10filesystem6detail6statusERKNS0_4pathEPNS_6system10error_codeE
  Referenced from: /usr/local/lib/libsdrpp_core.dylib
  Expected in: flat namespace

fish: Job 1, 'sdrpp' terminated by signal SIGABRT (Abandon)
`
I have tried on the 1.0.3 relesed and on the master git repo, same issue.

Any clue how to fix?

**Comment by Topper69** [comment]
To fix, do not edit any source file.
Just force ON the override option on the main CMakeLists.txt file.
`
# Compatibility Options
option(OPT_OVERRIDE_STD_FILESYSTEM "Use a local version of std::filesystem on systems that don't have it yet" ON)
`
